services:
  - type: web
    name: metr
    env: node
    buildCommand: yarn install --production=false && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_TELEMETRY_DISABLED
        value: 1